import numpy as np

TRANSDUCER_OFFSET = 0.0
HEIGHT = .1
SOUND_VELOCITY = 343
TRANSDUCER_RADIUS = .005
BASE_FREQ = 40000
T = 1/BASE_FREQ
WAVE_LENGTH = SOUND_VELOCITY/BASE_FREQ
BASE_AMP = 1
K = 2*np.pi/WAVE_LENGTH
CENTER = np.array([0,0,HEIGHT/2])
